module.exports = {
    help: "Guck ob die Shell funktioniert!\n/e - Generiere einen Fehler.\n/? - Zeige die Hilfe an.",
    permissionLevel: "user",
    run: function (args) {
        return new Promise((resolve, reject) => {
                if (args.includes("/e")) {
                    throw new Error("This is a test error generated by test.js")
                }
                resolve("Hello World!")
        })
    }
}